경북대 FE 7조 6주차 리뷰 요청입니다.
kakao-tech-campus-2nd-step3/Team7_FE pull request #41
Opened 2024-10-11 14:39 UTC by userjmmm

### ✨ 작업 내용

---

### ✨ 참고 사항

---

### ⏰ 현재 버그

---

### ✏ Git Close

2024-10-12 16:55 UTC, taehwanno requested changes
고생하셨어요. 피드백 드려요.

2024-10-12 16:55 UTC, taehwanno commented on .github/workflows/ci-cd.yml
> +    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/refactor/')
lint-and-test를 특정 브랜치에서만 실행하는 이유는 무엇일까요? push event 에서만 실행되고 있으니 가급적 모든 브랜치에서 lint-and-test가 실행되는게 좋겠습니다.

2024-10-12 16:55 UTC, taehwanno commented on src/components/Map/PlaceSection/index.tsx
> +  const { data: placeList } = useGetPlaceList(mapBounds, filters);
> 여기서 궁금한 점은 필터링을 통해 하위 컴포넌트끼리 값 공유가 필요할 경우, 상위 컴포넌트MapPage에서 state로 값을 관리하고, 상태를 끌어올리는 로직이 괜찮은 방법인지 궁금합니다!

query key가 동일한 요청이 동시에 발생했을 때 추가적인 http 요청을 발생시키지 않고 먼저 발생한 요청을 재활용합니다. 또한 이미 응답이 완료되었으며 적절한 staleTime, gcTime을 설정하면 http 요청을 발생시키지 않고도 여러 계층의 컴포넌트에서 원하는 데이터를 소비할 수 있습니다. 공식문서 한번 살펴보시면 좋을 거 같아요!

2024-10-12 16:55 UTC, taehwanno commented on src/components/My/UserPlaceSection/UserPlaceItem.tsx
> +  );
> src/components/My/UserPlaceSection/UserPlaceItem.tsx 코드의 handleClickLike 함수는 사용자에게 보이는 ui(❤️)만 변경하고 현재 페이지에선 실시간으로 변경되는 좋아요 여부가 반영되지 않고 있습니다.
>
> 백엔드로 요청을 보내는 로직이 있어서, 이후 새로고침하면 올바른 상태를 받아온다는 점에서 리소스 관리에 효율적이겠지만, 새로고침 하기 전까지 변경되는 상태가 반영되지 않는데 효율성과 안전성 측면에서 뭘 더 중요시해야 할지 궁금합니다.

GET을 제외한 메서드로 HTTP 요청을 성공하고 나서 적절한 UI로 변경해주는건 중요하기에 지금과 같은 상황에서는 백엔드에 요청 성공시 얼맞게 뷰를 업데이트 되도록 개선하는게 좋을 거 같습니다. 새로고침을 해야만 사용자가 자신의 행동에 대한 결과를 볼 수 있다면 Single Page Application의 장점을 살리지 못하는 구현이라 생각해요. 이건 효율성과 안전성의 문제라기 보다는 올바른 구현 방법을 찾지 못한 걸로 보이는데 어떤 어려움이 있으셨는지 조금 더 자세히 설명해주시겠어요?

UX 패턴 측면에서 설명을 조금 더 해둘게요. 유저 상호작용으로 인한 비동기 코드 실행시 완료되진 않았지만, 높은 확률도 업데이트 될 거라는 가정을 하고 UI를 미리 업데이트하는 패턴을 낙관적 업데이트 (optimistic update)라고 표현합니다. 해당 패턴을 사용할지 말지는 완료되지 않았지만 완료된 것처럼 보이는 행위가 서비스와 관련된 비즈니스 측면에서 크리티컬한 행동인지 아닌지에 따라 다를 수 있습니다. 인스타그램의 게시물에 하트 클릭시 성공을 가정하고 하트를 미리 변경했지만, 실패되어 하트가 표시되지 않는 다시 이전으로 돌아가는건 유저가 특정 게시물에 대한 관심도 표시 개수가 누락되는 정도라 인스타그램의 비즈니스와 사용자에게 크게 크리티컬 하지 않다고 볼 수도 있겠죠. 하지만 원자력 발전소의 관리 시스템을 가정했을 때 UI에서 특정 행동이 성공할 거라 가정하고 UI를 바로 최신화하는건 아주 크게 크리티컬 할 가능성이 높을 수 있겠습니다.

상황에 따라 다르니 개발자를 포함해서 보통은 프로덕트 매니저, 디자이너와 같이 논의해서 결정하는게 좋습니다. react-query 공식문서에서 낙관적 업데이트에 대한 문서 첨부해둘게요.

- https://tanstack.com/query/v5/docs/framework/react/guides/optimistic-updates

2024-10-12 16:55 UTC, taehwanno commented on src/pages/My/index.tsx
> +import { styled } from 'styled-components';
> 지난 pr까지 살아 있던(브랜치에 반영됨) component/feature을 삭제하고 PR을 올려서 merge를 진행했습니다. 그러나 폴더를 삭제해 충돌을 해결했는데도, merge가 되어서 weekly -> develop -> Master -> review 충돌을 일일히 해결했습니다. 이 방법말고 충돌을 1번만 해결해도 적용되는 등의 더 효율적인 방법이 있는지 궁금합니다.

조금 더 맥락이 필요할 거 같은데 아래 질문들 답변해주시겠어요?

1. 폴더 삭제는 어떤 브랜치를 기준으로 브랜치를 생성했나요?
2. 1번 브랜치에서 어떤 타겟 브랜치로 PR을 merge 했나요?
3. 충돌은 어떤 브랜치 사이에 발생했나요?

2024-10-12 16:55 UTC, taehwanno commented on src/hooks/useDetectClose.tsx
>    const ref = useRef<HTMLDivElement>(null);
지금은 `HTMLDivElement`에 결합되어 div 에서만 사용할 수 있네요. 해당 훅을 사용하는 외부에서 결정할 수 있도록 [Generic](https://www.typescriptlang.org/docs/handbook/2/generics.html)을 사용해볼 수 있을 거 같은데 한번 시도해보시겠어요?

2024-10-12 16:55 UTC, taehwanno commented on src/components/common/BaseLayout.tsx
> +import UserPlaceSection from '../My/UserPlaceSection';
여기서는 상대경로 사용하고 있네요. 프로젝트 전반적으로 import에서 `@/`으로 시작하는 절대경로를 사용하고 있으므로 개선되는게 좋겠습니다.

2024-10-13 09:55 UTC, userjmmm commented on .github/workflows/ci-cd.yml
> +    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/refactor/')
지난 멘토링 때 CI/CD 코드 내 포맷팅 필요성에 대한 답변을 들었을 때, PR에서 정적인 검사를 보장하기 위해 `lint-and-test`가 확실히 필요하다고 생각했습니다!
현재 저희 브랜치 전략은 기능 개발 브랜치, weekly, develop(검증용), Master(배포용 서버)를 사용하고, 동일한 코드가 순서대로 올라갑니다. 따라서 `merge 및 conflict`를 해결하는 동안 코드가 변경되는 가능성을 고려해 `weekly` 브랜치에는 추가하는 게 좋을 것 같습니다.

하지만 그 외 배포를 위한 브랜치는 `npm run build`를 수행하는데 이때 타입 검사, 잘못 작성된 자바스크립트 문법 검사도 처리하는 과정이 포매팅을 보장한다고 생각하여 필요하다고 생각하는 특정 브랜치만 `lint-and-test`를 실행했습니다. 혹시 이런 환경에서도 가급적 모든 브랜치에서 `lint-and-test`가 실행되는게 좋다고 생각하시는지 멘토님 의견을 여쭤보고 싶습니다:)

2024-10-13 11:05 UTC, userjmmm commented on src/pages/My/index.tsx
> +import { styled } from 'styled-components';
1. 저는 `refactor/#29-map-page`(기능 구현/수정) 브랜치를 기준으로 c653a12 커밋에서 폴더 삭제를 진행했습니다.
2. 폴더 삭제를 진행한 1번 `refactor` 브랜치에서, 각자 6주차에 작업한 내용을 모아두는 `weekly/6` 브랜치를 타겟으로 PR을 merge했습니다.
3. weekly -> develop -> Master -> review 순서로 각 브랜치 사이에서 동일한 충돌이 발생했습니다.

그 이유는 1번에서 언급한 브랜치에서 `component/feature` 폴더를 삭제했지만, merge 타겟 브랜치에는 여전히 해당 폴더가 존재해서라고 생각합니다.
PR을 확인하고 merge를 하면 두 브랜치의 변경 사항이 **통합**되는데, merge를 할 때마다 폴더를 삭제할지, 아니면 유지할지를 github가 직접 결정을 못하므로 충돌이 발생한 것 같습니다..

2024-10-14 08:03 UTC, userjmmm commented on src/components/common/BaseLayout.tsx
> +import UserPlaceSection from '../My/UserPlaceSection';
넵 일관성을 위해 4e840f4 에서 절대경로로 수정했습니다!

2024-10-14 14:17 UTC, taehwanno commented on .github/workflows/ci-cd.yml
> +    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/refactor/')
문법 검사, 타입 체크를 해주는 `npm run build`에서는 포매팅을 보장해주진 않을거에요 ㅎㅎ 더구나 테스트 실행은 정적 시점에 검출하기 힘든 런타임 에러가 있는지 없는지 검증해주는 역할도 lint-and-test에 있는 `Run tests`에서 하기 때문에 모든 브랜치에서 실행되는게 좋을 거 같습니다!

2024-10-14 14:19 UTC, taehwanno commented on src/pages/My/index.tsx
> +import { styled } from 'styled-components';
흠 희안하긴 하네요. 어떤 충돌이 발생하는지를 조금 더 살펴봐야 말씀드릴 수 있을 거 같네요.

2024-10-14 14:20 UTC, taehwanno approved these changes
기간상 병합해둘게요. 고생하셨습니다!

2024-10-18 04:35 UTC, merged