[1주차] 경북대 FE 7조 리뷰 요청입니다.
kakao-tech-campus-2nd-step3/Team7_FE pull request #7
Opened 2024-09-20 14:33 UTC by userjmmm

### ✨ 작업 내용
- 기초 세팅
  - [x] .eslintrc.cjs 재설정
  - [x] 패키지 추가 설치 및 버전 재설치

- 메인 페이지 컴포넌트 생성
  - [x] 인플루언서 컴포넌트 생성
  - [x] 컨텐츠 컴포넌트 생성
  - [x] 배너 컴포넌트 생성

- 여러 페이지에 필요한 컴포넌트 생성
  - [x] 상단바 생성
  - [x] 하단바 생성
  - [x] 검색바 생성
---

### ✨ 참고 사항
- 메인페이지 레이아웃까지 모두 설정 완료하였고, navigate나 data들은 임의로 설정해두었습니다. 추후 변경 예정
- ESLint 설정 구문 오류 때문에 ci/cd를 통과하지 못한 커밋이 있습니다. 확인 후 현재는 개발 속도를 위해 git action WorkFlow를 disabled한 상태입니다.
---

### ⏰ 질문 사항
- 검색바 컴포넌트를 생성한 코드에서 function의 파라미터로 SearchBarProps를 코드 내에 작성했습니다. 파라미터에 적힌 placeholder와 onchange는 데이터가 아닌 구조를 나타내는 게 더 적합하다고 생각해서 interface로 작성했는데요, type이 아닌 interface도 타입 정의한 코드 (type/index.tsx)에 작성하는 게 좋은지 궁금합니다.

2024-09-21 02:22 UTC, taehwanno requested changes
살펴보고 피드백드려요!

2024-09-21 02:22 UTC, taehwanno commented on package.json
> +    "@chakra-ui/react": "^2.8.2",
`npm run build` 실행시 아래처럼 에러가 발생하고 있네요. 개발 과정에서 빌드 가능한 상태로 유지하는건 중요하기에 개선되면 좋겠습니다.

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/b1e43f73-4ad2-4141-8cba-b178ada52d24">

2024-09-21 02:22 UTC, taehwanno commented on package.json
> +    "axios": "^1.7.7",
`npm run lint` 실행시 에러가 검출되고 있고 `npm run format` 적용되지 않은 코드도 있네요. 한번 수정해보시겠어요?

<img width="1860" alt="image" src="https://github.com/user-attachments/assets/5e0ab735-1740-41c4-9cde-10b3200d5485">

추가로 git commit 할 때 자동으로 prettier 적용, lint 검사 및 autofix 적용될 수 있게 [husky](https://typicode.github.io/husky/)와 [lint-staged](https://github.com/lint-staged/lint-staged) 적용하는게 좋을 거 같은데 한번 검토해봐주시겠어요?

2024-09-21 02:22 UTC, taehwanno commented on .github/workflows/ci-cd.yml
> +          fi
PR 본문에 설명해주셨듯 eslint 설정 구문 때문에 ci 쪽에서 lint를 비활성화 하신 것 같네요. 여러 팀원이 하나의 저장소에서 같이 작업한다면 코드 통합에 드는 비용을 낮추기 위해 CI를 브랜치 마다 계속 성공 상태로 만들어주는건 중요합니다. 그래서 CI가 통과될 수 있도록 개선해보는게 좋을 거 같은데 시도해보시겠어요?

2024-09-21 02:22 UTC, taehwanno commented on src/components/common/SearchBar.tsx
> +}
> 검색바 컴포넌트를 생성한 코드에서 function의 파라미터로 SearchBarProps를 코드 내에 작성했습니다. 파라미터에 적힌 placeholder와 onchange는 데이터가 아닌 구조를 나타내는 게 더 적합하다고 생각해서 interface로 작성했는데요, type이 아닌 interface도 타입 정의한 코드 (type/index.tsx)에 작성하는 게 좋은지 궁금합니다.

컴포넌트를 소비하는 코드 외부에서 컴포넌트 내부로 주입하는 props는 `types/index.tsx`로 분리하기보다는 지금처럼 컴포넌트 구현 코드 위에 적어주시는걸 추천드려요. 코드는 시간의 변화에 따라 같이 변화하는 정도를 의미하는 변화율에 따라 가깝게 위치시키는게 좋은데요, props는 말 그대로 컴포넌트에 전달해주는 함수 매개변수와 같은 의미를 가지고 있어서 컴포넌트 내부 변화로 인해 지원하는 매개변수가 아니라면 interface의 속성도 변화할테니까요. ([colocation](https://kentcdodds.com/blog/colocation) 글도 참고해보시면 좋을 거 같아요)

오히려 `types/index.ts`에서 관리할 코드의 기준을 조금 더 명확하게 하는게 좋겠습니다. 여러 컴포넌트에서 공통적으로 사용할 수 있는 데이터 구조를 의미하는거 같은데 이는 API 호출 코드를 구현하면서 자연스럽게 정리되지 않을까 싶긴 해요.

2024-09-21 02:22 UTC, taehwanno commented on package.json
> +    "@types/node": "^22.5.5",
폴더 구조는 어떤 식으로 구성되며 각 폴더에서 관리되는 코드의 기준은 무엇인지 `README.md`에 정리해볼 수 있을까요? 하나의 저장소에 여러 팀원이 같이 작업한다면 이러한 기준을 구체적으로 드러내서 프로젝트 초기에 정렬해두면 관점 차이 없이 개발하는 속도에 좋은 영향을 줄 수 있어요.

2024-09-23 12:26 UTC, taehwanno approved these changes
다음 단계 진행을 위해 시기상 병합해둘게요 ㅎㅎ 전달드린 피드백은 점진적으로 개선해보면 좋겠습니다. 화이팅입니다.

2024-09-23 12:26 UTC, merged

2024-09-26 14:44 UTC, Hyoeunkh commented on package.json
> +    "@chakra-ui/react": "^2.8.2",
b0fd0810a7e3f660f3bf1c748ead062dddfc0b7f
감사합니다